# -*- coding: utf-8 -*-
"""cevap3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXyAIK0qW8VR4S2zG-CevMOIBboppsIH
"""

def prime_first(k):
    
    if k >1: #asal 1 olamaz
        #bölünebiliyorsa asal değildir
        for i in range(2,k):
            if(k%i)==0:
                return

        print(k,end=" ")

def prime_second(k):
    
    for i in range(2,k):
        if(k%i)==0:
            return

    print(k,end=" ")
        

fonk1 = False
fonk2 = False
for i in range(0,1000):
   
    if i>=0 and i<500: #önce 0-500 arası
        if fonk1==False:
            print("prime_first: ",end=" ")
            fonk1 = True

        prime_first(i)
    else: #500-1000 arası için
        
        if fonk2==False:
            print("\n\nprime_second: ",end=" ")
            fonk2 = True

       
        prime_second(i)


print()