# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXyAIK0qW8VR4S2zG-CevMOIBboppsIH
"""

from random import randrange

matrix = [] 
satir2=0
uzunluk = 3
while satir2<uzunluk:
    #sıra oluştukça matris ekledim
    satir=[]
    num=0
    while num<uzunluk:
        n = 6*randrange(1,100)
        asal = True
        for i in range(2, int(n**.5)+1):
            if (n+1)%i == 0:
                asal = False
                break
        if asal:
            satir.append(n+1)
            num+=1
        if num<uzunluk:
            asal = True
            for i in range(2, int(n**.5)+1):
                if (n-1)%i == 0:
                    asal = False
                    break
            if asal:
                satir.append(n-1)
                num+=1
    
    matrix.append(satir)
    satir2+=1
    
#matrisi yazdırdım
for i in range(uzunluk):
    for j in range(uzunluk):
        print(f"{matrix[i][j]:>10}", end="   ")
    print("\n")