# -*- coding: utf-8 -*-
"""finalcevap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lPezwZJrBJDb_jKhlOJfZvLhSRCfG70k
"""

class YemekYap:
    def __init__(self):
        self.Ait = ""
        self.isim = ''
        self.malzemeler = []

    def yapılış(self):
        print("\nYapılma aşamaları", self.isim)

    def göster_malzemeler(self):
        print("Malzemeler şunlardır")
        for malzemeler in self.malzemeler:
            print(malzemeler)


class Tarif1(YemekYap):
    def __init__(self):
        super().__init__()
        self.Ait = "TURKIYE"
        self.malzemeler = ['kırmızı mercimek', 'soğan', 'un', 'havuç']
        self.isim = 'Mercimek Çorbası'

    def hazırlanış(self):
        super().göster_malzemeler()
        super().yapılış()
        print('\n1. Kırmızı mercimek çorbası için sıvı yağı tencereye alınarak yemeklik doğranan soğanlar hafif pembeleşinceye kadar kavrulur.')
        print('2.Daha sonra un ilave edilerek kısık ateşte kavurmaya devam edilir.')
        print( 'Salça kullanılacak ise salça ilave edilir, kavrulduktan sonra küp küp doğranmış havuç ve iyice yıkanıp suyu süzülen mercimekler ilave edilir.')
        print('4. Üzerine 1 lt su eklenerek karıştırılır ve tencerenin kapağı kapatılır. Mercimekler ve havuçlar yumuşayana kadar kısık ateşte pişirilir.')
        print('5. Mercimek çorbası servis kasesine alındıktan sonra üzerine kırmızı biberli sos gezdirilir ve bir dilim limon ile servis edilir.')
        print('\nAFİYET OLSUN!')


class Tarif2(YemekYap):
    def __init__(self):
        super().__init__()
        self.Ait = "Tamamen TURKIYE"
        self.malzemeler = ['petibör bisküvi', 'süt', 'un', 'mısır nişastası', 'toz şekerc', 'kakao',
                            'tereyağı', 'sütlü çikolata', 'vanilya']
        self.isim = 'Fakir Bisküvili Pasta'

    def hazırlanış(self):
        super().göster_malzemeler()
        super().yapılış()
        print( '1. Kremasını hazırlamak için, derin bir tencereye sütü alın. Üstüne unu, nişastayı, şekeri ve kakaoyu ekleyip bir tel çırpıcı yardımıyla güzelce karıştırın.\n\n')
        print(
            '2.Tencerenin altını açın ve sürekli karıştırarak, kaynamaya başlayıp, koyulana dek pişirin.\n\n')
        print('3.Göz göz kaynayıp, kıvamı koyulaşınca içine vanilyayı ekleyin karıştırın ve altını kapatın.\n\n')
        print('4.Altını kapattıktan sonra içine çikolatayı ve tereyağını ekleyip, tereyağı ve çikolata eriyene dek güzelce karıştırın.\n\n')
        print('5.Isıya dayanıklı kare bir kaba bir sıra petibör bisküvileri dizin, üstüne hazırladığınız kremadan bir kat dökün, bisküvileri örtecek şekilde.Üstüne tekrar bir sıra bisküvi dizin ve bu şekilde tüm krema bitene kadar devam edin.')
        print('\n\n6.Buzdolabına kaldırın ve 2-3 saat dinlendirdikten sonra dilimleyerek servis edin.')
        print('\nAFİYET OLSUN!')


if __name__ == '__main__':
    yemektarifi = Tarif2()
    yemektarifi.hazırlanış()